spring:
  application:
    name: project
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    open-in-view: false # 성능 최적화 및 N+1 문제 방지를 위해 false로 설정 (운영 권장)
    hibernate:
      physical-naming-strategy: org.hibernate.boot.model.naming.SpringPhysicalNamingStrategy # 물리적 네이밍 전략 설정
    properties:
      hibernate:
        format_sql: true # SQL 쿼리 포맷팅 (개발 환경에서 유용)
        highlight_sql: true # SQL 쿼리 하이라이팅 (개발 환경에서 유용)
    show-sql: true # 콘솔에 SQL 쿼리 출력 (개발 환경에서 유용)
